workspace:
  base: /go
  path: src/github.com/go-ggz/ggz

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: appleboy/golang-testing:1.9
    group: build
    commands:
      - cp .env.example .env
      - make embedmd
      - make fmt-check
      - make misspell-check
      - make test-vendor
      # - make stylesheets-check

  build:
    image: appleboy/golang-testing:1.9
    commands:
      - make docker_build
      - make tar

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
