workspace:
  base: /go
  path: src/github.com/alphabag/api

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: appleboy/golang-testing:1.9
    group: build
    commands:
      - cp env/env.drone .env
      - make embedmd
      - make fmt-check
      - make misspell-check
      - make test-vendor
      # - make stylesheets-check

  build:
    image: appleboy/golang-testing:1.9
    commands:
      - make generate
      - make docker_build
      - make tar

  scp:
    image: appleboy/drone-scp
    pull: true
    host: dev.fullinn.tw
    port: 22
    username: deploy
    target: /home/deploy/drone/${DRONE_REPO}
    secrets:
      - source: deploy_key
        target: scp_key
    source:
      - release.tar.gz
    when:
      branch: master

  ssh:
    image: appleboy/drone-ssh
    pull: true
    host: dev.fullinn.tw
    port: 22
    username: deploy
    command_timeout: 120
    secrets:
      - source: deploy_key
        target: ssh_key
    script:
      - rm -rf ${DRONE_REPO} && mkdir -p ${DRONE_REPO}
      - tar -zxmf /home/deploy/drone/${DRONE_REPO}/release.tar.gz -C ${DRONE_REPO}
      - cd ${DRONE_REPO} && make dev
    when:
      branch: master

  # scp:
  #   image: appleboy/drone-scp
  #   pull: true
  #   host: prod.fullinn.tw
  #   port: 22
  #   username: deploy
  #   target: /home/deploy/drone/${DRONE_REPO}
  #   secrets:
  #     - source: deploy_key
  #       target: scp_key
  #   source:
  #     - release.tar.gz
  #   when:
  #     event: tag

  # ssh:
  #   image: appleboy/drone-ssh
  #   pull: true
  #   host: prod.fullinn.tw
  #   port: 22
  #   username: deploy
  #   command_timeout: 120
  #   secrets:
  #     - source: deploy_key
  #       target: ssh_key
  #   script:
  #     - rm -rf ${DRONE_REPO} && mkdir -p ${DRONE_REPO}
  #     - tar -zxmf /home/deploy/drone/${DRONE_REPO}/release.tar.gz -C ${DRONE_REPO}
  #     - cd ${DRONE_REPO} && make prod
  #   when:
  #     event: tag

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
